# Generated by Django 4.0.10 on 2024-06-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_content_product_definition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='definition',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
