# Generated by Django 4.0.10 on 2024-06-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
