# Generated by Django 4.0.10 on 2024-06-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_brand_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='brands',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
