# Generated by Django 4.0.10 on 2024-06-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_faq_alter_brand_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner',
            field=models.ManyToManyField(to='products.banner'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(to='products.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='faq',
            field=models.ManyToManyField(to='products.faq'),
        ),
    ]
