# Generated by Django 4.0.10 on 2024-06-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_banner_product_brand_product_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
