# Generated by Django 4.0.10 on 2024-06-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_banner_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='content',
            new_name='subtitle',
        ),
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brands',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
