# Generated by Django 5.0.6 on 2024-06-26 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_rename_content_banner_subtitle_brand_name_faq_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='link_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='user_ru',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banner',
            name='user_uz',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='brands_ru',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brands_uz',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
