# Generated by Django 5.0.6 on 2024-06-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_banner_link_ru_banner_link_uz_banner_subtitle_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ru',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_uz',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='public_ru',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='public_uz',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
