# Generated by Django 5.0.6 on 2024-06-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_content_ru_product_content_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_uz',
        ),
    ]
