# Generated by Django 5.0.6 on 2024-06-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_product_image_ru_remove_product_image_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='link_ru',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='link_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='public_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='public_uz',
        ),
    ]
