# Generated by Django 5.0.6 on 2024-06-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_remove_banner_link_ru_remove_banner_link_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='user_ru',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='user_uz',
        ),
    ]
