# Generated by Django 5.0.6 on 2024-06-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_productretrieve_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productretrieve',
            old_name='weight',
            new_name='weights',
        ),
    ]
