# Generated by Django 5.0.6 on 2024-06-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_rename_weight_productretrieve_weights'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='weights',
        ),
    ]
