# Generated by Django 5.0.6 on 2024-06-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_delete_productretrieve_remove_product_banner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='subtitle_uz',
            new_name='subtitle_en',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='title_uz',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brands_uz',
            new_name='brands_en',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='name_uz',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='answer_uz',
            new_name='answer_en',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question_uz',
            new_name='question_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='content_uz',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_uz',
            new_name='title_en',
        ),
    ]
