# Generated by Django 5.0.6 on 2024-06-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_remove_productlist_banner_remove_productlist_brand_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductList',
        ),
    ]
