# Generated by Django 5.0.6 on 2024-06-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_categories_product_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
