# Generated by Django 5.0.6 on 2024-06-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_rename_categories_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categories',
            new_name='name',
        ),
    ]
