# Generated by Django 5.0.6 on 2024-07-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_alter_order_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=10000),
        ),
    ]
