# Generated by Django 5.0.6 on 2024-07-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_remove_product_order_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='count',
            new_name='quantity',
        ),
    ]
