# Generated by Django 5.0.6 on 2024-07-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_alter_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brands_en',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='brands_ru',
        ),
    ]
