# Generated by Django 5.0.6 on 2024-07-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_remove_brand_brands_en_remove_brand_brands_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cataloglist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.FileField(upload_to='products')),
            ],
        ),
    ]
