# Generated by Django 5.0.6 on 2024-07-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_cataloglist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cataloglist',
            new_name='Catalog',
        ),
    ]
