# Generated by Django 4.0.10 on 2024-07-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_remove_order_color_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(null=True, upload_to='banners'),
        ),
    ]
