# Generated by Django 4.0.10 on 2024-07-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
