# Generated by Django 4.0.10 on 2024-07-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0067_team_product_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='team',
        ),
    ]
