# Generated by Django 4.0.10 on 2024-07-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_remove_product_team'),
        ('products', '0068_remove_product_user'),
    ]

    operations = [
    ]
