# Generated by Django 4.0.10 on 2024-07-11 07:17

from django.db import migrations, models


def delete_mock_data(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Product.objects.all().delete()


def reverse_func(apps, schema_editor):
    ...


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0070_alter_product_title_alter_product_title_en_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_mock_data, reverse_func),
        migrations.AddField(
            model_name='product',
            name='guid',
            field=models.UUIDField(default='a5dc4374-fda4-47e7-8189-c2081cb6b8da'),
            preserve_default=False,
        ),
    ]
