# Generated by Django 4.0.10 on 2024-07-11 07:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0071_product_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
