# Generated by Django 4.0.10 on 2024-07-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_bestseller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestseller',
            name='product',
        ),
    ]
