# Generated by Django 4.0.10 on 2024-07-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0074_remove_bestseller_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestseller',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
