# Generated by Django 4.0.10 on 2024-07-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_product_stock'),
        ('products', '0075_bestseller_product'),
    ]

    operations = [
    ]
