# Generated by Django 4.0.10 on 2024-07-13 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0075_bestseller_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_ru',
        ),
    ]
