# Generated by Django 4.0.10 on 2024-07-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0076_merge_0073_product_stock_0075_bestseller_product'),
        ('products', '0076_remove_brand_name_en_remove_brand_name_ru'),
    ]

    operations = [
    ]
