# Generated by Django 4.0.10 on 2024-08-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0078_alter_category_options_category_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='productweight',
            name='price',
            field=models.FloatField(default=10.0),
        ),
    ]
