# Generated by Django 4.0.10 on 2024-08-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0081_rename_value_productweight_mass_alter_brand_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productweight',
            old_name='mass',
            new_name='value',
        ),
    ]
