# Generated by Django 4.0.10 on 2024-08-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0082_rename_mass_productweight_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productweight',
            name='price',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
    ]
