# Generated by Django 4.0.10 on 2024-08-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0083_alter_productweight_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productweight',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
