# Generated by Django 4.0.10 on 2024-08-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0085_remove_productweight_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characters',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Xarakteristika nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Xarakteristika qiymati'),
        ),
    ]
