# Generated by Django 4.0.10 on 2024-08-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0086_remove_product_characters_product_name_product_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productweight',
            name='mass',
            field=models.IntegerField(default=0),
        ),
    ]
