# Generated by Django 4.0.10 on 2024-08-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0087_alter_productweight_mass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='ch_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='value',
            new_name='ch_value',
        ),
    ]
