# Generated by Django 4.0.10 on 2024-08-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0089_rename_content_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productweight',
            name='mass',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
