# Generated by Django 4.0.10 on 2024-09-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0090_alter_productweight_mass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='color',
        ),
    ]
