# Generated by Django 4.0.10 on 2024-09-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0091_remove_productcolor_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productweight',
            name='mass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
