# Generated by Django 4.0.10 on 2024-09-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0092_alter_productweight_mass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
