# Generated by Django 4.2.16 on 2024-10-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0094_remove_product_color_remove_product_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='productprice',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Ostatka'),
        ),
    ]
