# Generated by Django 4.2.16 on 2024-10-03 04:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0095_remove_product_stock_productprice_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='guid',
        ),
        migrations.AddField(
            model_name='productprice',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
