# Generated by Django 4.2.16 on 2024-10-03 05:24

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0096_remove_product_guid_productprice_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_image_upload_path),
        ),
    ]
