# Generated by Django 4.2.16 on 2024-10-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0098_productprice_external_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='artikul',
        ),
        migrations.AddField(
            model_name='productprice',
            name='artikul',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
