# Generated by Django 4.2.16 on 2024-10-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0101_alter_orderitem_color_alter_orderitem_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ru',
        ),
        migrations.AddField(
            model_name='productprice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
