# Generated by Django 4.2.16 on 2024-10-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0102_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'parent')},
        ),
    ]
