# Generated by Django 4.2.16 on 2024-10-31 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0105_remove_brand_category_brand_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestseller',
            name='product_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productprice'),
        ),
    ]
