# Generated by Django 4.2.16 on 2024-10-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0106_bestseller_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestseller',
            name='product_price',
        ),
        migrations.AddField(
            model_name='bestseller',
            name='product_price',
            field=models.ManyToManyField(to='products.productprice'),
        ),
    ]
