# Generated by Django 4.2.16 on 2024-11-20 08:29

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0110_alter_productshots_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshots',
            name='image',
            field=models.ImageField(null=True, upload_to=products.models.get_image_upload_path),
        ),
    ]
