# Generated by Django 4.2.16 on 2025-09-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0111_alter_productshots_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='artikul',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='artikul'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='external_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productweight',
            name='mass',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
